apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.name }}-custom-env
  namespace: {{ .Values.global.namespace  | quote}}
data:
  CURRENCY: {{ .Values.decidim.env.CURRENCY | 6b64enc }}
  DECIDIM_HALF_SIGNUP_SHOW_TOS_PAGE_AFTER_SIGNUP: {{ .Values.decidim.env.DECIDIM_HALF_SIGNUP_SHOW_TOS_PAGE_AFTER_SIGNUP | 6b64enc }}
  DECIDIM_SESSION_TIMEOUT: {{ .Values.decidim.env.DECIDIM_SESSION_TIMEOUT | 6b64enc }}
  ENABLE_RACK_ATTACK: {{ .Values.decidim.env.ENABLE_RACK_ATTACK | 6b64enc }}
  GEOCODER_LOOKUP_API_KEY: {{ .Values.decidim.env.GEOCODER_LOOKUP_API_KEY | 6b64enc }}
  HALF_SIGNUP_SKIP_CSRF: {{ .Values.decidim.env.HALF_SIGNUP_SKIP_CSRF | 6b64enc }}
  HELP_SCOUT_BEACON_ID_MAIN: {{ .Values.decidim.env.HELP_SCOUT_BEACON_ID_MAIN | 6b64enc }}
  OMNIAUTH_SETTINGS_FACEBOOK_APP_ID: {{ .Values.decidim.env.OMNIAUTH_SETTINGS_FACEBOOK_APP_ID | 6b64enc }}
  OMNIAUTH_SETTINGS_FACEBOOK_APP_SECRET: {{ .Values.decidim.env.OMNIAUTH_SETTINGS_FACEBOOK_APP_SECRET | 6b64enc }}
  OMNIAUTH_SETTINGS_FACEBOOK_ENABLED: {{ .Values.decidim.env.OMNIAUTH_SETTINGS_FACEBOOK_ENABLED | 6b64enc }}
  OMNIAUTH_SETTINGS_FRANCE_CONNECT_CLIENT_ID: {{ .Values.decidim.env.OMNIAUTH_SETTINGS_FRANCE_CONNECT_CLIENT_ID | 6b64enc }}
  OMNIAUTH_SETTINGS_FRANCE_CONNECT_CLIENT_SECRET: {{ .Values.decidim.env.OMNIAUTH_SETTINGS_FRANCE_CONNECT_CLIENT_SECRET | 6b64enc }}
  OMNIAUTH_SETTINGS_FRANCE_CONNECT_ENABLED: {{ .Values.decidim.env.OMNIAUTH_SETTINGS_FRANCE_CONNECT_ENABLED | 6b64enc }}
  OMNIAUTH_SETTINGS_FRANCE_CONNECT_PROFILE_BUTTON_PATH: {{ .Values.decidim.env.OMNIAUTH_SETTINGS_FRANCE_CONNECT_PROFILE_BUTTON_PATH | 6b64enc }}
  OMNIAUTH_SETTINGS_FRANCE_CONNECT_PROFILE_CLIENT_ID: {{ .Values.decidim.env.OMNIAUTH_SETTINGS_FRANCE_CONNECT_PROFILE_CLIENT_ID | 6b64enc }}
  OMNIAUTH_SETTINGS_FRANCE_CONNECT_PROFILE_CLIENT_SECRET: {{ .Values.decidim.env.OMNIAUTH_SETTINGS_FRANCE_CONNECT_PROFILE_CLIENT_SECRET | 6b64enc }}
  OMNIAUTH_SETTINGS_FRANCE_CONNECT_PROFILE_ENABLED: {{ .Values.decidim.env.OMNIAUTH_SETTINGS_FRANCE_CONNECT_PROFILE_ENABLED | 6b64enc }}
  OMNIAUTH_SETTINGS_FRANCE_CONNECT_PROFILE_ICON_PATH: {{ .Values.decidim.env.OMNIAUTH_SETTINGS_FRANCE_CONNECT_PROFILE_ICON_PATH | 6b64enc }}
  OMNIAUTH_SETTINGS_FRANCE_CONNECT_PROFILE_PROVIDER_NAME: {{ .Values.decidim.env.OMNIAUTH_SETTINGS_FRANCE_CONNECT_PROFILE_PROVIDER_NAME | 6b64enc }}
  OMNIAUTH_SETTINGS_FRANCE_CONNECT_PROFILE_SITE: {{ .Values.decidim.env.OMNIAUTH_SETTINGS_FRANCE_CONNECT_PROFILE_SITE | 6b64enc }}
  OMNIAUTH_SETTINGS_FRANCE_CONNECT_SITE_URL: {{ .Values.decidim.env.OMNIAUTH_SETTINGS_FRANCE_CONNECT_SITE_URL | 6b64enc }}
  OMNIAUTH_SETTINGS_FRANCE_CONNECT_UID_BUTTON_PATH: {{ .Values.decidim.env.OMNIAUTH_SETTINGS_FRANCE_CONNECT_UID_BUTTON_PATH | 6b64enc }}
  OMNIAUTH_SETTINGS_FRANCE_CONNECT_UID_CLIENT_ID: {{ .Values.decidim.env.OMNIAUTH_SETTINGS_FRANCE_CONNECT_UID_CLIENT_ID | 6b64enc }}
  OMNIAUTH_SETTINGS_FRANCE_CONNECT_UID_CLIENT_SECRET: {{ .Values.decidim.env.OMNIAUTH_SETTINGS_FRANCE_CONNECT_UID_CLIENT_SECRET | 6b64enc }}
  OMNIAUTH_SETTINGS_FRANCE_CONNECT_UID_ENABLED: {{ .Values.decidim.env.OMNIAUTH_SETTINGS_FRANCE_CONNECT_UID_ENABLED | 6b64enc }}
  OMNIAUTH_SETTINGS_FRANCE_CONNECT_UID_ICON_PATH: {{ .Values.decidim.env.OMNIAUTH_SETTINGS_FRANCE_CONNECT_UID_ICON_PATH | 6b64enc }}
  OMNIAUTH_SETTINGS_FRANCE_CONNECT_UID_PROVIDER_NAME: {{ .Values.decidim.env.OMNIAUTH_SETTINGS_FRANCE_CONNECT_UID_PROVIDER_NAME | 6b64enc }}
  OMNIAUTH_SETTINGS_FRANCE_CONNECT_UID_SITE: {{ .Values.decidim.env.OMNIAUTH_SETTINGS_FRANCE_CONNECT_UID_SITE | 6b64enc }}
  OMNIAUTH_SETTINGS_GOOGLE_OAUTH2_CLIENT_ID: {{ .Values.decidim.env.OMNIAUTH_SETTINGS_GOOGLE_OAUTH2_CLIENT_ID | 6b64enc }}
  OMNIAUTH_SETTINGS_GOOGLE_OAUTH2_CLIENT_SECRET: {{ .Values.decidim.env.OMNIAUTH_SETTINGS_GOOGLE_OAUTH2_CLIENT_SECRET | 6b64enc }}
  OMNIAUTH_SETTINGS_GOOGLE_OAUTH2_ENABLED: {{ .Values.decidim.env.OMNIAUTH_SETTINGS_GOOGLE_OAUTH2_ENABLED | 6b64enc }}
  OMNIAUTH_SETTINGS_PUBLIK_CLIENT_ID: {{ .Values.decidim.env.OMNIAUTH_SETTINGS_PUBLIK_CLIENT_ID | 6b64enc }}
  OMNIAUTH_SETTINGS_PUBLIK_CLIENT_SECRET: {{ .Values.decidim.env.OMNIAUTH_SETTINGS_PUBLIK_CLIENT_SECRET | 6b64enc }}
  OMNIAUTH_SETTINGS_PUBLIK_ENABLED: {{ .Values.decidim.env.OMNIAUTH_SETTINGS_PUBLIK_ENABLED | 6b64enc }}
  OMNIAUTH_SETTINGS_PUBLIK_SITE_URL: {{ .Values.decidim.env.OMNIAUTH_SETTINGS_PUBLIK_SITE_URL | 6b64enc }}
  OMNIAUTH_SETTINGS_TWITTER_API_KEY: {{ .Values.decidim.env.OMNIAUTH_SETTINGS_TWITTER_API_KEY | 6b64enc }}
  OMNIAUTH_SETTINGS_TWITTER_API_SECRET: {{ .Values.decidim.env.OMNIAUTH_SETTINGS_TWITTER_API_SECRET | 6b64enc }}
  OMNIAUTH_SETTINGS_TWITTER_ENABLED: {{ .Values.decidim.env.OMNIAUTH_SETTINGS_TWITTER_ENABLED | 6b64enc }}
  PERFORM_BLOCK_USER: {{ .Values.decidim.env.PERFORM_BLOCK_USER | 6b64enc }}
  RAILS_ENV: {{ .Values.decidim.env.RAILS_ENV | 6b64enc }}
  RAILS_LOG_LEVEL: {{ .Values.decidim.env.RAILS_LOG_LEVEL | 6b64enc }}
  SMS_GATEWAY_MB_ACCOUNT_ID: {{ .Values.decidim.env.SMS_GATEWAY_MB_ACCOUNT_ID | 6b64enc }}
  SMS_GATEWAY_MB_API_KEY: {{ .Values.decidim.env.SMS_GATEWAY_MB_API_KEY | 6b64enc }}
  SMS_GATEWAY_OADC: {{ .Values.decidim.env.SMS_GATEWAY_OADC | 6b64enc }}
  SMS_GATEWAY_SERVICE: {{ .Values.decidim.env.SMS_GATEWAY_SERVICE | 6b64enc }}
  SMS_GATEWAY_URL: {{ .Values.decidim.env.SMS_GATEWAY_URL | 6b64enc }}
  SMTP_ADDRESS: {{ .Values.decidim.env.SMTP_ADDRESS | 6b64enc }}
  SMTP_FROM: {{ .Values.decidim.env.SMTP_FROM | 6b64enc }}
  SMTP_FROM_EMAIL: {{ .Values.decidim.env.SMTP_FROM_EMAIL | 6b64enc }}
  SMTP_FROM_LABEL: {{ .Values.decidim.env.SMTP_FROM_LABEL | 6b64enc }}
  SMTP_PASSWORD: {{ .Values.decidim.env.SMTP_PASSWORD | 6b64enc }}
  SMTP_PORT: {{ .Values.decidim.env.SMTP_PORT | 6b64enc }}
  SMTP_USER_NAME: {{ .Values.decidim.env.SMTP_USER_NAME | 6b64enc }}
  SORT_PROCESSES_BY_DATE: {{ .Values.decidim.env.SORT_PROCESSES_BY_DATE | 6b64enc }}
  SPAM_DETECTION_API_AUTH_TOKEN: {{ .Values.decidim.env.SPAM_DETECTION_API_AUTH_TOKEN | 6b64enc }}
  SPAM_DETECTION_API_URL: {{ .Values.decidim.env.SPAM_DETECTION_API_URL | 6b64enc }}
type: Opaque
